// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Dtde3IQ3ZTJS9URF7w4pA4dBX_0jrUs',
    appId: '1:489997114843:web:a541a0b681060c161fdbfe',
    messagingSenderId: '489997114843',
    projectId: 'arcscope-ac787',
    authDomain: 'arcscope-ac787.firebaseapp.com',
    storageBucket: 'arcscope-ac787.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD155NCt3rUqSzXR7uOovRy3NPIgBdVqHA',
    appId: '1:489997114843:android:70c9b7da2b07e05b1fdbfe',
    messagingSenderId: '489997114843',
    projectId: 'arcscope-ac787',
    storageBucket: 'arcscope-ac787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH2mmMgy7_beP4DGMdcwvUJmsxm63UNRk',
    appId: '1:489997114843:ios:ce799cc2a746fffc1fdbfe',
    messagingSenderId: '489997114843',
    projectId: 'arcscope-ac787',
    storageBucket: 'arcscope-ac787.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH2mmMgy7_beP4DGMdcwvUJmsxm63UNRk',
    appId: '1:489997114843:ios:ce799cc2a746fffc1fdbfe',
    messagingSenderId: '489997114843',
    projectId: 'arcscope-ac787',
    storageBucket: 'arcscope-ac787.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Dtde3IQ3ZTJS9URF7w4pA4dBX_0jrUs',
    appId: '1:489997114843:web:d5c6279e531f3ce91fdbfe',
    messagingSenderId: '489997114843',
    projectId: 'arcscope-ac787',
    authDomain: 'arcscope-ac787.firebaseapp.com',
    storageBucket: 'arcscope-ac787.firebasestorage.app',
  );
}
